package com.data_management;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;


/**
 * Reads patient data from output files generated by the simulator and
 * loads it into the DataStorage system.
 *
 * format:
 * Patient ID: X, Timestamp: X, Label: X, Data: X
 */
public class FileDataReader implements DataReader {

    private final String directoryPath;

    public FileDataReader(String directoryPath) {
        this.directoryPath = directoryPath;
    }

    /**
     * Reads all files in the given directory, parses each line,
     * and stores the extracted data into DataStorage.
     *
     * @param dataStorage the storage for the parsed data
     * @throws IOException if file reading fails
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {

        try (Stream<Path> files = Files.list(Path.of(directoryPath))) {

            files.filter(Files::isRegularFile).forEach(file -> {

                try (BufferedReader reader = new BufferedReader(new FileReader(file.toFile()))) {

                    String line;

                    while ((line = reader.readLine()) != null) {

                        //continue if the line is empty
                        if (line.trim().isEmpty()) continue;

                        // Add the data to the datastorage
                        String[] parts = line.split(",");
                        int patientId = Integer.parseInt(parts[0].split(":")[1].trim());
                        long timestamp = Long.parseLong(parts[1].split(":")[1].trim());
                        String recordType = parts[2].split(":")[1].trim();
                        double value = Double.parseDouble(parts[3].split(":")[1].trim());

                        dataStorage.addPatientData(patientId, value, recordType, timestamp);
                    }

                } catch (Exception e) {
                    System.err.println("Error reading file: " + file + " -> " + e.getMessage());
                }
            });

        }
    }
}